# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Cache Toolchain
      id: cache-toolchain
      uses: actions/cache@v2.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: toolchain
        key: ${{ runner.os }}-toolchain
    
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        cp defconfig .config
        ./build.sh
        
    - name: Upload kernel
      uses: actions/upload-artifact@v2
      with:
        name: pocophone_kernel
        path: output/pocophone_kernel.zip
